### ISSUE TITLE
trax/opencv.hpp: No such file or directory

### ISSUE THREAD

**Issue by minglinlu** [lukacu/mil#1]
[ 87%] Building CXX object CMakeFiles/mil.dir/src/BoostTrackMain.cpp.o
/Users/lml/Desktop/CPP/mil/src/BoostTrackMain.cpp:10:27: fatal error: trax/opencv.hpp: No such file or directory

> hey man, I wanna know where is the `trax/opencv.hpp`, are you using the openCv 2.4 or 3+, in my case open-cv-2.4.10 is not working on mac os 10.12

**Comment by lukacu** [comment]
Well, you need TraX library with OpenCV support (can be enabled when compiling the library) installed.
